// <auto-generated />
using System;
using ENSEK.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ENSEK.DataAccess.Migrations
{
    [DbContext(typeof(MeterReadingsDbContext))]
    [Migration("20210422221830_add-more-seed-data")]
    partial class addmoreseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ENSEK.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec42fc64-7264-4e23-874e-855b9a73db28"),
                            AccountId = 2344,
                            FirstName = "Tommy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("81f17936-4ed0-41cf-8f8e-38ae3702b1f6"),
                            AccountId = 2233,
                            FirstName = "Barry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("105ce48b-ee7a-439b-817c-4a927698f1cd"),
                            AccountId = 8766,
                            FirstName = "Sally",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("b1825046-dbaa-4b45-93e7-e32ef55f4ccf"),
                            AccountId = 2345,
                            FirstName = "Jerry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("2cfdb621-9441-4a74-ad7e-4db6c4ad0d55"),
                            AccountId = 2346,
                            FirstName = "Ollie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("cc5c8640-8d44-41e2-b319-e124927a136c"),
                            AccountId = 2347,
                            FirstName = "Tara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("fcca5f02-bd37-4278-843f-18863a4f529f"),
                            AccountId = 2348,
                            FirstName = "Tammy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("6f0f6ca4-f4a8-464a-b2b8-340944f1415e"),
                            AccountId = 2349,
                            FirstName = "Simon",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("72ccde40-9309-4659-88c8-7db6de34b78c"),
                            AccountId = 2350,
                            FirstName = "Colin",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("685cf5f7-1d28-473f-a6c4-0299ec965217"),
                            AccountId = 2351,
                            FirstName = "Gladys",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("e3f5d8db-1c2c-4007-9a55-d8dca71c3ca6"),
                            AccountId = 2352,
                            FirstName = "Greg",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("5ec79839-cd8b-431c-be0f-ea9fbee4eb51"),
                            AccountId = 2353,
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("141ad736-f525-4bbc-8ef9-8898602b65bd"),
                            AccountId = 2356,
                            FirstName = "Craig",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("cf5f2112-a840-4160-9e91-079529e65d64"),
                            AccountId = 6776,
                            FirstName = "Laura",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("ff8ddb59-24ef-4df5-b111-186981a20d77"),
                            AccountId = 4354,
                            FirstName = "Josh",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("23cdabb5-2a70-4914-a521-0fdc8699381f"),
                            AccountId = 1234,
                            FirstName = "Freya",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("fa379fee-d384-48d0-95c1-ee764f87da28"),
                            AccountId = 1239,
                            FirstName = "Noddy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("bbe8a8e8-8c52-4435-8012-6e70135bea34"),
                            AccountId = 1240,
                            FirstName = "Archie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("5a22881f-f1fe-4955-bba1-29ce1999a3ae"),
                            AccountId = 1241,
                            FirstName = "Lara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("f4e3539c-ae42-4faa-ac05-a25ed5cdb40b"),
                            AccountId = 1242,
                            FirstName = "Tim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("92322413-6038-45a9-b65b-a004b4a84ee9"),
                            AccountId = 1243,
                            FirstName = "Graham",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("b576d2e1-3db6-4b9e-bb31-03763c3c4669"),
                            AccountId = 1244,
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("6a300289-15a8-4193-8cbe-0f66063a7e4f"),
                            AccountId = 1245,
                            FirstName = "Neville",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("5645bd1a-0461-4792-8c9a-e4a051923b0c"),
                            AccountId = 1246,
                            FirstName = "Jo",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("2ca32105-4704-408f-a301-984c02d706f6"),
                            AccountId = 1247,
                            FirstName = "Jim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = new Guid("32a55030-b1ad-4806-af95-b452642cfb92"),
                            AccountId = 1248,
                            FirstName = "Pam",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("ENSEK.DataAccess.Entities.MeterReadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AccountId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeterReadValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeterReadingDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId1");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("ENSEK.DataAccess.Entities.MeterReadingEntity", b =>
                {
                    b.HasOne("ENSEK.DataAccess.Entities.AccountEntity", "Account")
                        .WithMany("MeterReadings")
                        .HasForeignKey("AccountId1");
                });
#pragma warning restore 612, 618
        }
    }
}
